#!/bin/sh

# Find the directory this script is in
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Call the Julia script with the same arguments
julia "$SCRIPT_DIR/populate_geoids.jl" "$@" 