name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'  # Minimum supported Julia version
          - '1'    # Latest stable 1.x release
        os:
          - ubuntu-latest
        arch:
          - x64
    services:
      postgres:
        image: postgis/postgis:13-3.1
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: geocoder
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - name: Create census schema and tables
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d geocoder -c "CREATE SCHEMA IF NOT EXISTS census;"
          PGPASSWORD=postgres psql -h localhost -U postgres -d geocoder -c "
            CREATE TABLE IF NOT EXISTS census.counties (
              geoid VARCHAR(5) PRIMARY KEY,
              name VARCHAR(100),
              stusps VARCHAR(2),
              geom GEOMETRY(MultiPolygon, 4269)
            );"
      - name: Set environment variables
        run: |
          echo "GEOIDS_DB_NAME=geocoder" >> $GITHUB_ENV
          echo "GEOIDS_DB_HOST=localhost" >> $GITHUB_ENV
          echo "GEOIDS_DB_PORT=5432" >> $GITHUB_ENV
          echo "GEOIDS_DB_USER=postgres" >> $GITHUB_ENV
          echo "GEOIDS_DB_PASSWORD=postgres" >> $GITHUB_ENV
      - uses: julia-actions/julia-runtest@v1
        env:
          GEOIDS_DB_NAME: geocoder
          GEOIDS_DB_HOST: localhost
          GEOIDS_DB_PORT: 5432
          GEOIDS_DB_USER: postgres
          GEOIDS_DB_PASSWORD: postgres
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          file: lcov.info 